-- ██████╗ ██╗     ██╗                   ███╗   ███╗██╗   ██╗███████╗ ██████╗ ██╗     
-- ██╔══██╗██║     ██║                   ████╗ ████║╚██╗ ██╔╝██╔════╝██╔═══██╗██║     
-- ██████╔╝██║     ██║         █████╗    ██╔████╔██║ ╚████╔╝ ███████╗██║   ██║██║     
-- ██╔══██╗██║     ██║         ╚════╝    ██║╚██╔╝██║  ╚██╔╝  ╚════██║██║▄▄ ██║██║     
-- ██║  ██║███████╗███████╗              ██║ ╚═╝ ██║   ██║   ███████║╚██████╔╝███████╗
-- ╚═╝  ╚═╝╚══════╝╚══════╝              ╚═╝     ╚═╝   ╚═╝   ╚══════╝ ╚══▀▀═╝ ╚══════╝

SELECT "Hello, World!";

-- Admin module
-- -- Location feature
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Delhi', 'Delhi', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Mumbai', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kolkata', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bandalore', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Chennai', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hyderabad', 'Telangana', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Pune', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Ahmedabad', 'Gujrat', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Surat', 'Gujrat', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Prayagraj', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Lucknow', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Rajasthan', 'Jaipur', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kanpur', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Mirzapur', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Maharashtra', 'Nagpur', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Ghaziabad', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Vadodara', 'Gujrat', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Vishakhapatnam', 'Andhra Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Indore', 'Madhya Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Thane', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bhopal', 'Madhya Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Patna', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bilaspur', 'Chhattisgarh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Ludhiana', 'Punjab', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Agra', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Madurai', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Jamshedpur', 'Jharkhand', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nasik', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Faridabad', 'Haryana', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Aurangabad', 'Madhya Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Rajkot', 'Gujrat', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Meerut', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Jabalpur', 'Madhya Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kalamboli', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Vasai', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Varanasi', 'Uttar Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Srinagar', 'Jammu and Kashmir', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Dhanbad', 'Jharkhand', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Amritsar', 'Punjab', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Guwahati', 'Assam', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hawra', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Ranchi', 'Jharkhan', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Gwalior', 'Madhya Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Chandigarh', 'Chandigarh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Vijayvada', 'Andhra Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Jodhpur', 'Rajasthan', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Raipur', 'Chhattisgarh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kota', 'Rajasthan', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bhayandar', 'Maharashtra', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Salt Lake City', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Darbhanga', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Dasarhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'New Delhi', 'Delhi', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Puducherry', 'Puducherry', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Pallavaram', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Shimla', 'Himachal Pradesh', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Puri', 'Odisha', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Shrirampur', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hugli', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Krishna Nagar', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Barakpur', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nangloi Jat', 'Delhi', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Yelahanka', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Tilagarh',  'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Dam Dam', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bansbaria', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Madhavaram', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Baj Baj', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nerkunram', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kendraparha', 'Odisha', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sijua', 'Jharkhand', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Manali', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Chakapara', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Pappakurichchi', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Herohalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Madipakkam', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sabalpur', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Salua', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Balasore', 'Odisha', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Chinnasekkadu', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Jethuli', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nagtala', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Pakri', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hunasamaranhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hesarghatta', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bommayapalaiyam', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Gundur', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Punadi', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hariladi', 'Jharkhand', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Alawalpur', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Madnaikanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kadiganahalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Mahuli', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Arshakunti', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Hirapur', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Mirchi', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sonudi', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sondekoppa', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Babura', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kadabgeri', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nanmangalam', 'Tamil Nadu', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Taliganja', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Tarchha', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Belgharia', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kammanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sonnappanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kedihati', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Doddajivanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Simli Murarpur', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Sonawan', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Devanandapur', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Tribeni', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Huttanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Nathupur', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bali', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Vajarhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Saino', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Shekhpura', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Chachohalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Narayanpur Kola', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Gyan Chak', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kasgatpur', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kitanelli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Harchandi', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Santoshpur', 'West Bengal', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Bendravadi', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Kodagihalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Harna Bujurg', 'Bihar', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
INSERT INTO admin_location (terminal, city, province, date_modified, date_created) VALUES('', 'Mailanhalli', 'Karnataka', TIMESTAMP(NOW()), TIMESTAMP(NOW()));
