server:
  port: 8888

spring:
  application:
    name: "emedicare-cloud-config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/harshrathod50/rll-cloud-config-server.git"
          username: ""
          password: ""
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"
