server:
  port: 0

spring:
  profiles:
    active: "dev"
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: main
  application:
    name: payment-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    preferIpAddress: false
