server:
  port:
    0

spring:
  application:
    name: "user-login-service"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      label: "main"  


eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
  instance:
    preferIpAddress: false

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      product-microservice:
        # sliding-window-type: "time-based"
        sliding-window-type: "count-based"
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: "10s"
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    retry-aspect-order: 2
    instances:
      product-microservice:
        max-attempts: 3
        wait-duration: "2s"
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5
